using DME
using Test

include("test_util.jl")
include("test_data_series.jl")
include("test_fred.jl")
include("test_preprocess.jl")
include("test_ramsey.jl")
include("test_rbc.jl")
include("test_solow.jl")
include("test_islm.jl")
include("test_adas.jl")
include("test_new_keynesian.jl")
include("test_var.jl")
include("test_mundell_fleming.jl")
include("test_simulation_result.jl")
include("test_analysis_context.jl")
include("test_doc_context.jl")
include("test_prompts.jl")
include("test_provider.jl")
include("test_visualization.jl")
include("test_quality.jl")
